<a href="https://colab.research.google.com/github/garrick-watkins/MIS-433/blob/main/Copy_of_assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (int(f) - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 30
30
30F is -1.1111111111111112 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = input('Please enter the temperature in Celcius: ')

print(c)

f = (int(c) * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')
#print(str(c)+C is '+str(f)+' in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60
60C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
if m == 'C':
  c = d
  f = (int(c) * 9/5) + 32
  print(f'{c}C is {f} in Fahrenheit. ')

else:
  f = d
  c = (int(f) - 32) * 5/9
  print(f'{f}F is {c} in Celsius. ')


Please enter the temperature: 30
Is this in Celsius or Fahrenheit? F
30F is -1.1111111111111112 in Celsius. 


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print(len(sentence))

48


In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[10:(len(sentence)-10)])

eap. Show me the code - Linu


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('.','').replace('-','').split(' '))

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', '', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
for v in vowels:
  b = sentence.lower().count(v)
  print(f'{v} = {b}')

a = 3
e = 4
i = 2
o = 3
u = 1


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
      print(sentence[i], i)

a 1
i 5
e 10
a 11
o 17
e 21
e 25
o 28
e 30
i 35
u 37
o 41
a 44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
list_cubes = [i**3 for i in range(5)]
print(list_cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowel = 'aeiou'
[i for i in range(len(sentence)) if sentence[i] in vowel]

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]

In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')

# add your code here
a=0
b=1
for i in range(int(n)):
  fibonacci.append(a)
  a, b = b, a + b

print(fibonacci)

How many numbers do you want? 5
[0, 1, 1, 2, 3]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer': 0.95, 'Moderna' : 0.95, 'AstraZeneca' : 0.72, 'Johnson & Johnson' : 0.66}

In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(f'The efficacy of {v} is {v_dict[v]}')

Which vaccine? Pfizer
The efficacy of Pfizer is 0.95


In [ ]:
from decorator import append
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
S = {'Sputnik V' : 0.914}
v_dict.update(S)
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
si = {'Sinovac' : 0.5038}
v_dict.update(si)
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [ ]:
# Print vaccines with efficacy lower than 90%.
for k, v in v_dict.items():
  if v < 0.9:
    print(k)

AstraZeneca
Johnson & Johnson
Sinovac


In [ ]:
# delete the Sinovac vaccine from the dictionary.
v_dict.pop('Sinovac')
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'
sentence = sentence.replace(' ','')
ch_dict = {}
for ch in sentence:
  if ch in ch_dict:
    ch_dict[ch] += 1
  else:
    ch_dict[ch] = 1
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [3]:
import numpy as np

In [4]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([])
np.arange(2,41,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [5]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([])
np.arange(1,40,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [6]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

(10, 10)

In [11]:
# Count the numbers in M with an absolute value greater than 1.
np.count_nonzero(np.absolute(M) > 1)

33

In [12]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
while True:
  r = input('Row count: ')
  if int(r) <= 3:
    print('Rows must be 3 or greater. Try again.')
  else:
    break

# Input the number of rows (input another integer >= 3)
while True:
  c = input('Column count: ')
  if int(c) <= 3:
    print('Columns must be 3 or greater. Try again.')
  else:
    break

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
arr

Row count: 4
Column count: 4


array([[10, 10, 11, 14],
       [16, 14, 16, 19],
       [11, 15, 10, 16],
       [15, 11, 11, 11]])

In [16]:
# output the element in the first row and the third column
print(arr[0,2])

11


In [15]:
# output the element in the second row and the last column
print(arr[1, arr.shape[1]-1])

19


In [17]:
# output the second row of the array
print(arr[1])

[16 14 16 19]


In [18]:
# output the second last row of the array
print(arr[arr.shape[1]-1])

[15 11 11 11]


In [22]:
# output the second column of the array
print(arr[:, 0])

[10 16 11 15]


In [24]:
# output the second last column of the array
print(arr[:, arr.shape[1]-1])

[14 19 16 11]


In [25]:
# output the upper-left 3x3 sub-array
print(arr[:3, :3])

[[10 10 11]
 [16 14 16]
 [11 15 10]]


In [26]:
# output the bottom-left 3x3 sub-array
print(arr[arr.shape[1]-3:, :3])

[[16 14 16]
 [11 15 10]
 [15 11 11]]


In [27]:
# output the upper-right 3x3 sub-array
print(arr[:3, arr.shape[1]-3:])

[[10 11 14]
 [14 16 19]
 [15 10 16]]


In [28]:
# output the bottom-right 3x3 sub-array
print(arr[arr.shape[1]-3:, arr.shape[1]-3:])

[[14 16 19]
 [15 10 16]
 [11 11 11]]


In [54]:
# Create a 1-D array from 1 to 50 (inclusive)
A = numbers = list(range(1, 51))
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]

A = np.array(A).reshape(5,10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [55]:
b = np.arange(51, 61).reshape(1, -1)
A = np.vstack((A, b))
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [56]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:2, :]
A2 = A[2:, :]
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [57]:
# Add 10 to each element of A
A = (A + 10)
print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [58]:
# Calculate the square root of each element in A
print(np.sqrt(A))

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [59]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [60]:
# Print the mean, standard devietion of all numbers in M
print(M.mean())
print(M.std())

0.08081337363915245
1.0379069118910227


In [61]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print("Maximum:           ", np.max(M))
print("25th percentile:   ", np.percentile(M, 25))
print("Median:            ", np.median(M))
print("75th percentile:   ", np.percentile(M, 75))
print("Minimum:           ", np.min(M))

Maximum:            3.188941367264205
25th percentile:    -0.663298925613999
Median:             0.0601811305606987
75th percentile:    0.6690313306532156
Minimum:            -2.402645149557677
